// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class BNBLicenceManager;


/** This class incapsulates information about Client Token.  */
@interface BNBLicenceManager : NSObject

/** Creates *new* `LicenceManager`. This metod won't change Banuba SDK internal state. */
+ (nullable BNBLicenceManager *)create:(nonnull NSString *)clientToken;

/**
 * Returns the instance used by Banuba SDK to check licence. 
 * This istance was created by `UtilityManager.initialize`.
 */
+ (nullable BNBLicenceManager *)instance;

/** Checks if Client Token is expired.  */
- (BOOL)isExpired;

/** Returns decoded content of Client Token */
- (nonnull NSString *)getJson;

@end
