// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from neuro_beauty.djinni

#import "BNBLipsMorphingMode.h"
#import "BNBNeuroBeautyOutput.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBNeuroBeauty;


@interface BNBNeuroBeauty : NSObject

+ (nullable BNBNeuroBeauty *)create;

- (BOOL)preprocessPhoto:(nonnull BNBFullImageData *)sourceImage;

- (nullable BNBNeuroBeautyOutput *)applyTextures:(nonnull NSString *)lutPath
                                        onlySkin:(BOOL)onlySkin
                                        tonePath:(nonnull NSString *)tonePath
                                         eyePath:(nonnull NSString *)eyePath
                                  applyScleraMod:(BOOL)applyScleraMod
                              applyEyeFiltration:(BOOL)applyEyeFiltration
                                     eyelashPath:(nonnull NSString *)eyelashPath
                               applyLipsMorphing:(BOOL)applyLipsMorphing
                                    morphingMode:(BNBLipsMorphingMode)morphingMode
                                    morphingCoef:(float)morphingCoef;

- (void)resetFeature;

- (void)runPerfTest;

- (nullable BNBNeuroBeautyOutput *)executeF0:(nonnull BNBFullImageData *)sourceImage
                                      amount:(float)amount
                                      radius:(float)radius;

- (nullable BNBNeuroBeautyOutput *)executeF1:(nonnull BNBFullImageData *)sourceImage
                                  brightness:(float)brightness
                                    contrast:(float)contrast
                                   useLegacy:(BOOL)useLegacy;

- (nullable BNBNeuroBeautyOutput *)executeF2:(nonnull BNBFullImageData *)sourceImage
                                    strength:(float)strength
                              noiseAlgorithm:(int32_t)noiseAlgorithm
                               monochromatic:(BOOL)monochromatic;

- (nullable BNBNeuroBeautyOutput *)executeF3:(nonnull BNBFullImageData *)sourceImage
                                  saturation:(float)saturation;

@end
